//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.BattleShip.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BattleShipEntities : DbContext
    {
        public BattleShipEntities()
            : base("name=BattleShipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameHit> GameHits { get; set; }
        public virtual DbSet<MapShip> MapShips { get; set; }
        public virtual DbSet<PlayerGame> PlayerGames { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerShip> PlayerShips { get; set; }
        public virtual DbSet<ShipCell> ShipCells { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
