//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.BattleShip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameHit
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public Nullable<int> ShipCellId { get; set; }
        public byte X_Pos { get; set; }
        public byte Y_Pos { get; set; }
    
        public virtual PlayerGame PlayerGame { get; set; }
        public virtual ShipCell ShipCell { get; set; }
    }
}
