//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.BattleShip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipCell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipCell()
        {
            this.GameHits = new HashSet<GameHit>();
        }
    
        public int Id { get; set; }
        public int ShipId { get; set; }
        public Nullable<byte> X_Pos { get; set; }
        public Nullable<byte> Y_Pos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameHit> GameHits { get; set; }
        public virtual MapShip MapShip { get; set; }
    }
}
