// <auto-generated />
namespace Academy.BattleShip.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Current3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Current3));
        
        string IMigrationMetadata.Id
        {
            get { return "201606091948440_Current3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
